In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df_prouni = pd.read_excel('/content/cursos-prouni.csv.xlsx')
df_prouni

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,cidade_filtro,universidade_nome,campus_nome,campus_external_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,MS,NTAwMjAwNDAyNzA0,Universidade Anhanguera - UNIDERP,CAMPO GRANDE - SEDE - Miguel Couto,706710,Medicina,740.22,726.46,NaN,NaN
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Enfermagem,663.36,NaN,NaN,NaN
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,SP,MzUxNTA2MTUwMzA4,Universidade Cidade de São Paulo - UNICID,UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...,1002328,Medicina,739.62,738.08,738.96,718.64
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Psicologia,651.00,652.22,NaN,NaN
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,AC,MTIwMjAwNDAwNDAx,Faculdade Barão do Rio Branco - FAB,CAMPUS - RIO BRANCO - JARDIM EUROPA II - Jard...,658996,Medicina,758.32,723.94,734.92,711.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41442,Licenciatura,Curso a Distância,149.00,1.0,NaN,NaN,NaN,994312865605,Sociologia,Paraiso do Tocantins,TO,MTcwMTAwNDE2MTA5,Universidade Paulista - UNIP,PARAISO DO TOCANTINS - Centro,9943,Sociologia,502.36,NaN,NaN,NaN
41443,Tecnológico,Curso a Distância,144.00,1.0,2.0,2.0,5.0,65868712869275,Marketing,Sao VIcente,SP,MzUxNTA2MzUxMDA5,Faculdade de São VIcente - FSV,UNIDADE SEDE - Centro,658687,Marketing,533.34,450.00,450.00,450.00
41444,Tecnológico,Vespertino,139.00,1.0,NaN,NaN,NaN,1056445674232,Gestão de Recursos Humanos,Brasilia,DF,NTMwMTAwMTAwMTA4,Centro Universitário Planalto do Distrito Fede...,DF03 - UNIDADE BRASIL CENTRAL - Taguatinga Nor...,1056445,Gestão de Recursos Humanos,580.76,NaN,NaN,NaN
41445,Bacharelado,Curso a Distância,139.00,1.0,NaN,NaN,NaN,96781210935,Serviço Social,Vitoria,ES,MzIwMzAwOTA1MzA5,Universidade Paulista - UNIP,VITORIA I - Barro Vermelho,9678,Serviço Social,548.26,NaN,NaN,NaN
41446,Tecnológico,Curso a Distância,139.00,3.0,1.0,NaN,NaN,200467412868575,Gestão Ambiental,Santarem,PA,MTUwMTAwMjA2ODA3,Universidade Paulista - UNIP,SANTARÉM - Fátima,2004674,Gestão Ambiental,605.32,573.70,NaN,NaN

//Busca do curso por estado

In [6]:
pd.crosstab(df_prouni.uf_busca, df_prouni.curso_busca)

curso_busca,Administração,Administração Pública,Administração de Empresas,Administração de Recursos Humanos,Agroindústria,Agronegócio,Agronomia,Agropecuária,Alimentos,Análise e Desenvolvimento de Sistemas,...,Teologia,Terapia Ocupacional,Tradutor e Intérprete,Turismo,Turismo Receptivo,Turismo e Hotelaria,Visagismo e Terapias Capilares,Viticultura e Enologia,Zootecnia,Óptica e Optometria
uf_busca,,,,,,,,,,,,,,,,,,,,,
AC,12,0,0,0,0,0,0,0,0,7,...,2,0,0,0,0,0,0,0,0,0
AL,19,0,0,0,0,1,0,0,0,9,...,4,0,0,2,0,0,0,0,0,0
AM,24,1,0,0,0,1,0,0,0,10,...,4,0,0,0,0,0,0,0,0,0
AP,12,0,0,0,0,1,0,0,0,6,...,3,0,0,3,0,0,0,0,0,0
BA,194,4,0,0,0,7,2,0,2,47,...,31,0,0,8,0,0,0,2,0,0
CE,74,0,0,0,0,0,0,0,0,21,...,6,0,0,4,0,0,0,0,0,0
DF,64,0,0,0,0,0,3,0,0,38,...,14,0,0,2,0,0,0,0,0,0
ES,69,0,0,0,0,5,0,0,0,14,...,8,0,0,2,1,0,0,0,0,0
GO,99,0,0,0,0,10,8,0,0,31,...,14,0,0,2,0,0,0,0,1,0
MA,49,1,0,0,0,2,0,0,0,16,...,8,0,0,3,0,0,0,0,1,0
MG,294,0,1,0,0,21,14,0,0,78,...,57,0,0,7,2,0,0,0,2,0
MS,71,0,0,0,0,21,5,0,0,15,...,15,0,0,2,1,0,0,0,1,0
MT,70,0,0,0,0,17,7,0,0,35,...,17,0,0,2,1,0,0,0,1,0
PA,81,1,0,0,0,0,1,0,0,39,...,18,1,0,2,0,0,0,0,1,0
PB,39,0,0,0,0,0,2,0,0,11,...,4,0,0,2,0,0,0,0,0,0
PE,92,1,0,0,0,0,0,0,0,27,...,10,0,0,6,0,0,0,0,0,0
PI,34,0,0,0,0,0,0,0,0,9,...,2,2,0,2,0,0,0,0,0,0
PR,255,1,0,0,1,11,31,0,0,89,...,88,1,0,6,0,0,0,0,0,0
RJ,110,0,0,0,0,2,0,0,0,33,...,28,0,0,3,0,0,0,0,0,0
RN,34,0,0,0,0,0,0,0,0,5,...,3,0,0,0,0,0,0,0,0,0
RO,33,0,0,0,0,1,3,0,0,10,...,5,1,0,0,0,0,0,0,1,0
RR,6,0,0,0,0,0,0,0,0,4,...,3,0,0,0,0,0,0,0,0,0
RS,230,2,0,0,0,11,16,1,0,84,...,53,1,0,3,0,0,0,0,0,0
SC,118,3,0,0,0,9,8,0,1,56,...,38,0,0,2,1,1,0,0,1,0
SE,27,0,0,0,0,0,0,0,0,7,...,1,0,0,2,0,0,0,0,0,0
SP,616,7,0,7,0,20,14,0,1,295,...,133,6,6,28,0,0,2,0,2,2
TO,28,0,0,0,0,3,4,0,0,12,...,4,0,0,2,0,0,0,0,0,0

//Busca do curso por estado com o subtotal por linhas: parâmetro (margins = True)

In [7]:
pd.crosstab(df_prouni.uf_busca, df_prouni.curso_busca, margins = True)

curso_busca,Administração,Administração Pública,Administração de Empresas,Administração de Recursos Humanos,Agroindústria,Agronegócio,Agronomia,Agropecuária,Alimentos,Análise e Desenvolvimento de Sistemas,...,Terapia Ocupacional,Tradutor e Intérprete,Turismo,Turismo Receptivo,Turismo e Hotelaria,Visagismo e Terapias Capilares,Viticultura e Enologia,Zootecnia,Óptica e Optometria,All
uf_busca,,,,,,,,,,,,,,,,,,,,,
AC,12,0,0,0,0,0,0,0,0,7,...,0,0,0,0,0,0,0,0,0,203
AL,19,0,0,0,0,1,0,0,0,9,...,0,0,2,0,0,0,0,0,0,327
AM,24,1,0,0,0,1,0,0,0,10,...,0,0,0,0,0,0,0,0,0,429
AP,12,0,0,0,0,1,0,0,0,6,...,0,0,3,0,0,0,0,0,0,219
BA,194,4,0,0,0,7,2,0,2,47,...,0,0,8,0,0,0,2,0,0,2505
CE,74,0,0,0,0,0,0,0,0,21,...,0,0,4,0,0,0,0,0,0,816
DF,64,0,0,0,0,0,3,0,0,38,...,0,0,2,0,0,0,0,0,0,1063
ES,69,0,0,0,0,5,0,0,0,14,...,0,0,2,1,0,0,0,0,0,825
GO,99,0,0,0,0,10,8,0,0,31,...,0,0,2,0,0,0,0,1,0,1278
MA,49,1,0,0,0,2,0,0,0,16,...,0,0,3,0,0,0,0,1,0,679
MG,294,0,1,0,0,21,14,0,0,78,...,0,0,7,2,0,0,0,2,0,4175
MS,71,0,0,0,0,21,5,0,0,15,...,0,0,2,1,0,0,0,1,0,785
MT,70,0,0,0,0,17,7,0,0,35,...,0,0,2,1,0,0,0,1,0,1063
PA,81,1,0,0,0,0,1,0,0,39,...,1,0,2,0,0,0,0,1,0,1201
PB,39,0,0,0,0,0,2,0,0,11,...,0,0,2,0,0,0,0,0,0,596
PE,92,1,0,0,0,0,0,0,0,27,...,0,0,6,0,0,0,0,0,0,1148
PI,34,0,0,0,0,0,0,0,0,9,...,2,0,2,0,0,0,0,0,0,405
PR,255,1,0,0,1,11,31,0,0,89,...,1,0,6,0,0,0,0,0,0,3918
RJ,110,0,0,0,0,2,0,0,0,33,...,0,0,3,0,0,0,0,0,0,1442
RN,34,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,342
RO,33,0,0,0,0,1,3,0,0,10,...,1,0,0,0,0,0,0,1,0,463
RR,6,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,111
RS,230,2,0,0,0,11,16,1,0,84,...,1,0,3,0,0,0,0,0,0,3060
SC,118,3,0,0,0,9,8,0,1,56,...,0,0,2,1,1,0,0,1,0,2195
SE,27,0,0,0,0,0,0,0,0,7,...,0,0,2,0,0,0,0,0,0,323
SP,616,7,0,7,0,20,14,0,1,295,...,6,6,28,0,0,2,0,2,2,11533
TO,28,0,0,0,0,3,4,0,0,12,...,0,0,2,0,0,0,0,0,0,343
All,2754,21,1,7,1,143,118,1,4,1008,...,12,6,95,6,1,2,2,11,2,41447

In [8]:
pd.crosstab(df_prouni.uf_busca, [df_prouni.curso_busca, df_prouni['nota_integral_ampla']], margins = True)

curso_busca         Administração                                            \
nota_integral_ampla         450.0 452.94 456.44 461.26 461.84 462.44 466.16
uf_busca
AC                              0      0      0      0      0      0      0
AL                              0      0      0      0      0      0      0
AM                              0      0      0      0      0      0      0
AP                              0      0      0      0      0      0      0
BA                              1      0      0      0      0      0      0
CE                              0      0      0      0      0      0      0
DF                              0      0      0      0      0      0      0
ES                              0      0      0      0      0      0      0
GO                              1      0      0      0      0      0      0
MA                              0      0      0      0      0      0      0
MG                              0      0      0      0      0      1      0
MS                              2      0      0      0      0      0      0
MT                              2      0      0      1      1      0      0
PA                              1      0      0      0      0      0      0
PB                              0      0      0      0      0      0      0
PE                              0      0      0      0      0      0      0
PI                              0      0      0      0      0      0      0
PR                              5      0      0      0      0      0      0
RJ                              1      0      0      0      0      0      0
RN                              0      0      0      0      0      0      0
RO                              0      0      0      0      0      0      0
RR                              0      0      0      0      0      0      0
RS                              3      0      0      0      0      0      0
SC                              3      0      1      0      0      0      0
SE                              0      0      0      0      0      0      0
SP                             34      1      0      0      0      0      1
TO                              0      0      0      0      0      0      0
All                            53      1      1      1      1      1      1

curso_busca                              ... Zootecnia                     \
nota_integral_ampla 466.34 467.26 468.5  ...    597.58 604.0 610.4 612.96
uf_busca                                 ...
AC                       0      0     0  ...         0     0     0      0
AL                       0      0     0  ...         0     0     0      0
AM                       0      0     0  ...         0     0     0      0
AP                       0      0     0  ...         0     0     0      0
BA                       0      0     0  ...         0     0     0      0
CE                       0      0     0  ...         0     0     0      0
DF                       0      0     0  ...         0     0     0      0
ES                       0      0     0  ...         0     0     0      0
GO                       0      0     0  ...         0     0     0      0
MA                       0      0     0  ...         0     0     0      0
MG                       0      0     0  ...         0     0     1      1
MS                       0      0     0  ...         0     0     0      0
MT                       0      0     0  ...         0     0     0      0
PA                       0      0     0  ...         0     0     0      0
PB                       0      0     0  ...         0     0     0      0
PE                       1      0     0  ...         0     0     0      0
PI                       0      0     0  ...         0     0     0      0
PR                       0      0     0  ...         0     0     0      0
RJ                       0      0     0  ...         0     0     0      0
RN                       0      0     0  ...         0     0     0      0
RO                       0      0     0  ...         0     0     0      0
RR                       0      0     0  ...         0     0     0      0
RS                       0      0     0  ...         0     0     0      0
SC                       0      0     0  ...         0     0     0      0
SE                       0      0     0  ...         0     0     0      0
SP                       0      1     1  ...         1     1     0      0
TO                       0      0     0  ...         0     0     0      0
All                      1      1     1  ...         1     1     1      1

curso_busca                              Óptica e Optometria           All
nota_integral_ampla 624.76 633.02 634.46              584.84 656.82
uf_busca
AC                       0      0      0                   0      0    157
AL                       0      0      0                   0      0    274
AM                       0      0      0                   0      0    347
AP                       0      0      0                   0      0    174
BA                       0      0      0                   0      0   1916
CE                       0      0      0                   0      0    604
DF                       0      0      0                   0      0    908
ES                       0      0      0                   0      0    667
GO                       0      1      0                   0      0   1007
MA                       0      0      0                   0      0    527
MG                       0      0      0                   0      0   3295
MS                       1      0      0                   0      0    590
MT                       0      0      0                   0      0    803
PA                       0      0      1                   0      0    852
PB                       0      0      0                   0      0    515
PE                       0      0      0                   0      0    918
PI                       0      0      0                   0      0    348
PR                       0      0      0                   0      0   2746
RJ                       0      0      0                   0      0   1221
RN                       0      0      0                   0      0    304
RO                       0      0      0                   0      0    385
RR                       0      0      0                   0      0     95
RS                       0      0      0                   0      0   2448
SC                       0      0      0                   0      0   1600
SE                       0      0      0                   0      0    296
SP                       0      0      0                   1      1   9231
TO                       0      0      0                   0      0    292
All                      1      1      1                   1      1  32520

[28 rows x 28668 columns]

In [12]:
pd.crosstab([df_prouni.uf_busca], [df_prouni.curso_busca], values=df_prouni.nota_integral_ampla, aggfunc= (np.sum), margins = True)

curso_busca,Administração,Administração Pública,Administração de Empresas,Administração de Recursos Humanos,Agroindústria,Agronegócio,Agronomia,Agropecuária,Alimentos,Análise e Desenvolvimento de Sistemas,...,Terapia Ocupacional,Tradutor e Intérprete,Turismo,Turismo Receptivo,Turismo e Hotelaria,Visagismo e Terapias Capilares,Viticultura e Enologia,Zootecnia,Óptica e Optometria,All
uf_busca,,,,,,,,,,,,,,,,,,,,,
AC,4230.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3554.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92994.28
AL,10039.94,NaN,NaN,NaN,NaN,557.34,NaN,NaN,NaN,4261.36,...,NaN,NaN,1169.92,NaN,NaN,NaN,NaN,NaN,NaN,163877.92
AM,11524.62,577.44,NaN,NaN,NaN,584.14,NaN,NaN,NaN,3964.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201403.38
AP,5751.96,NaN,NaN,NaN,NaN,573.08,NaN,NaN,NaN,1820.36,...,NaN,NaN,1649.36,NaN,NaN,NaN,NaN,NaN,NaN,101582.44
BA,82503.26,2347.02,NaN,NaN,NaN,3427.94,1259.22,NaN,1125.16,15899.54,...,NaN,NaN,2815.02,NaN,NaN,NaN,1024.6,NaN,NaN,1128413.14
CE,36759.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8667.36,...,NaN,NaN,1229.14,NaN,NaN,NaN,NaN,NaN,NaN,380810.46
DF,30060.30,NaN,NaN,NaN,NaN,NaN,1845.36,NaN,NaN,20383.78,...,NaN,NaN,1230.92,NaN,NaN,NaN,NaN,NaN,NaN,532211.88
ES,36014.80,NaN,NaN,NaN,NaN,2653.72,NaN,NaN,NaN,5995.98,...,NaN,NaN,1151.58,573.78,NaN,NaN,NaN,NaN,NaN,404031.58
GO,47022.78,NaN,NaN,NaN,NaN,3882.20,4304.40,NaN,NaN,10547.32,...,NaN,NaN,1150.04,NaN,NaN,NaN,NaN,633.02,NaN,577100.24
MA,23828.72,581.58,NaN,NaN,NaN,1167.66,NaN,NaN,NaN,7166.98,...,NaN,NaN,571.42,NaN,NaN,NaN,NaN,569.46,NaN,320692.54
MG,150570.00,NaN,638.42,NaN,NaN,11501.40,8734.42,NaN,NaN,29658.22,...,NaN,NaN,4203.64,1114.86,NaN,NaN,NaN,1223.36,NaN,1952482.10
MS,29818.82,NaN,NaN,NaN,NaN,5522.78,3002.66,NaN,NaN,3289.30,...,NaN,NaN,1169.90,532.66,NaN,NaN,NaN,624.76,NaN,327197.24
MT,29478.62,NaN,NaN,NaN,NaN,6961.52,4074.12,NaN,NaN,8704.64,...,NaN,NaN,1145.70,515.86,NaN,NaN,NaN,583.68,NaN,434100.16
PA,40219.70,557.40,NaN,NaN,NaN,NaN,674.94,NaN,NaN,13072.32,...,651.98,NaN,1169.26,NaN,NaN,NaN,NaN,634.46,NaN,501206.80
PB,20497.94,NaN,NaN,NaN,NaN,NaN,1119.74,NaN,NaN,5433.00,...,NaN,NaN,1171.38,NaN,NaN,NaN,NaN,NaN,NaN,311204.40
PE,48049.00,611.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10693.44,...,NaN,NaN,3539.46,NaN,NaN,NaN,NaN,NaN,NaN,549025.36
PI,17894.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3668.24,...,606.30,NaN,1123.20,NaN,NaN,NaN,NaN,NaN,NaN,210761.62
PR,111243.54,490.84,NaN,NaN,570.52,5593.80,16849.34,NaN,NaN,33281.52,...,560.08,NaN,3335.92,NaN,NaN,NaN,NaN,NaN,NaN,1545992.80
RJ,59240.62,NaN,NaN,NaN,NaN,1190.02,NaN,NaN,NaN,14257.48,...,NaN,NaN,1915.90,NaN,NaN,NaN,NaN,NaN,NaN,739500.36
RN,17706.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3077.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184698.68
RO,14857.94,NaN,NaN,NaN,NaN,582.86,1789.80,NaN,NaN,5199.74,...,560.58,NaN,NaN,NaN,NaN,NaN,NaN,565.70,NaN,222247.48
RR,2842.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2153.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53061.38
RS,110872.50,1135.22,NaN,NaN,NaN,5800.62,8547.10,579.02,NaN,36505.06,...,608.48,NaN,1803.38,NaN,NaN,NaN,NaN,NaN,NaN,1389033.18
SC,48321.36,1560.56,NaN,NaN,NaN,3587.16,4232.50,NaN,560.72,18006.24,...,NaN,NaN,1104.68,508.12,559.12,NaN,NaN,590.42,NaN,868118.46
SE,16010.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3488.80,...,NaN,NaN,1122.16,NaN,NaN,NaN,NaN,NaN,NaN,177738.74
SP,298373.60,3266.44,NaN,3913.54,NaN,10667.38,6009.48,NaN,547.72,136764.54,...,3624.18,3589.02,15429.70,NaN,NaN,1172.6,NaN,1201.58,1241.66,5192331.20
TO,12407.64,NaN,NaN,NaN,NaN,1119.08,2473.00,NaN,NaN,5290.74,...,NaN,NaN,1156.96,NaN,NaN,NaN,NaN,NaN,NaN,169149.30
All,1316141.50,11127.62,638.42,3913.54,570.52,65372.70,64916.08,579.02,2233.60,414806.90,...,6611.60,3589.02,50358.64,3245.28,559.12,1172.6,1024.6,6626.44,1241.66,18730967.12

In [14]:
pd.crosstab([df_prouni.uf_busca], [df_prouni.curso_busca], values=df_prouni.nota_integral_ampla, aggfunc= (np.median), margins = True)

curso_busca,Administração,Administração Pública,Administração de Empresas,Administração de Recursos Humanos,Agroindústria,Agronegócio,Agronomia,Agropecuária,Alimentos,Análise e Desenvolvimento de Sistemas,...,Terapia Ocupacional,Tradutor e Intérprete,Turismo,Turismo Receptivo,Turismo e Hotelaria,Visagismo e Terapias Capilares,Viticultura e Enologia,Zootecnia,Óptica e Optometria,All
uf_busca,,,,,,,,,,,,,,,,,,,,,
AC,608.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,594.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,588.78
AL,581.96,NaN,NaN,NaN,NaN,557.34,NaN,NaN,NaN,599.56,...,NaN,NaN,584.96,NaN,NaN,NaN,NaN,NaN,NaN,592.33
AM,572.87,577.44,NaN,NaN,NaN,584.14,NaN,NaN,NaN,578.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.90
AP,573.57,NaN,NaN,NaN,NaN,573.08,NaN,NaN,NaN,587.40,...,NaN,NaN,548.16,NaN,NaN,NaN,NaN,NaN,NaN,581.16
BA,582.98,588.91,NaN,NaN,NaN,574.93,629.61,NaN,562.58,594.38,...,NaN,NaN,568.62,NaN,NaN,NaN,512.3,NaN,NaN,587.99
CE,622.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,621.86,...,NaN,NaN,614.57,NaN,NaN,NaN,NaN,NaN,NaN,630.08
DF,583.79,NaN,NaN,NaN,NaN,NaN,614.68,NaN,NaN,593.84,...,NaN,NaN,615.46,NaN,NaN,NaN,NaN,NaN,NaN,589.83
ES,603.56,NaN,NaN,NaN,NaN,526.66,NaN,NaN,NaN,595.90,...,NaN,NaN,575.79,573.78,NaN,NaN,NaN,NaN,NaN,605.74
GO,571.72,NaN,NaN,NaN,NaN,544.98,622.34,NaN,NaN,595.12,...,NaN,NaN,575.02,NaN,NaN,NaN,NaN,633.02,NaN,576.02
MA,595.49,581.58,NaN,NaN,NaN,583.83,NaN,NaN,NaN,600.10,...,NaN,NaN,571.42,NaN,NaN,NaN,NaN,569.46,NaN,607.28
MG,593.32,NaN,638.42,NaN,NaN,562.92,622.82,NaN,NaN,596.66,...,NaN,NaN,592.94,557.43,NaN,NaN,NaN,611.68,NaN,595.14
MS,555.63,NaN,NaN,NaN,NaN,526.78,592.60,NaN,NaN,558.85,...,NaN,NaN,584.95,532.66,NaN,NaN,NaN,624.76,NaN,561.97
MT,550.76,NaN,NaN,NaN,NaN,543.70,565.80,NaN,NaN,553.41,...,NaN,NaN,572.85,515.86,NaN,NaN,NaN,583.68,NaN,545.00
PA,583.32,557.40,NaN,NaN,NaN,NaN,674.94,NaN,NaN,588.41,...,651.98,NaN,584.63,NaN,NaN,NaN,NaN,634.46,NaN,584.34
PB,579.62,NaN,NaN,NaN,NaN,NaN,559.87,NaN,NaN,604.88,...,NaN,NaN,585.69,NaN,NaN,NaN,NaN,NaN,NaN,604.24
PE,589.19,611.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.48,...,NaN,NaN,590.96,NaN,NaN,NaN,NaN,NaN,NaN,596.58
PI,598.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,614.59,...,606.30,NaN,561.60,NaN,NaN,NaN,NaN,NaN,NaN,599.62
PR,569.97,490.84,NaN,NaN,570.52,553.39,605.42,NaN,NaN,587.88,...,560.08,NaN,558.16,NaN,NaN,NaN,NaN,NaN,NaN,568.30
RJ,604.77,NaN,NaN,NaN,NaN,595.01,NaN,NaN,NaN,597.35,...,NaN,NaN,631.96,NaN,NaN,NaN,NaN,NaN,NaN,605.46
RN,589.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609.68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,601.86
RO,571.15,NaN,NaN,NaN,NaN,582.86,594.14,NaN,NaN,576.04,...,560.58,NaN,NaN,NaN,NaN,NaN,NaN,565.70,NaN,575.34
RR,559.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,540.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,551.84
RS,570.60,567.61,NaN,NaN,NaN,530.04,613.74,579.02,NaN,566.04,...,608.48,NaN,601.72,NaN,NaN,NaN,NaN,NaN,NaN,571.62
SC,560.90,500.08,NaN,NaN,NaN,506.12,606.88,NaN,560.72,535.21,...,NaN,NaN,552.34,508.12,559.12,NaN,NaN,590.42,NaN,546.89
SE,594.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,589.24,...,NaN,NaN,561.08,NaN,NaN,NaN,NaN,NaN,NaN,597.52
SP,565.94,450.00,NaN,559.9,NaN,543.75,604.03,NaN,547.72,575.43,...,607.66,605.12,578.10,NaN,NaN,586.3,NaN,600.79,620.83,569.54
TO,572.46,NaN,NaN,NaN,NaN,559.54,615.50,NaN,NaN,580.38,...,NaN,NaN,578.48,NaN,NaN,NaN,NaN,NaN,NaN,573.78
All,578.22,544.02,638.42,559.9,570.52,548.10,607.38,579.02,561.53,580.32,...,606.30,605.12,580.20,534.51,559.12,586.3,512.3,604.00,620.83,580.74

// Nova coluna. Definição que o df2 será uma cópia desse novo df

In [15]:
df_prouni['total_bolsas'] = df_prouni.bolsa_integral_ampla + df_prouni.bolsa_integral_cotas

df2 = df_prouni.copy()
df2

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,...,cidade_filtro,universidade_nome,campus_nome,campus_external_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas,total_bolsas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,...,NTAwMjAwNDAyNzA0,Universidade Anhanguera - UNIDERP,CAMPO GRANDE - SEDE - Miguel Couto,706710,Medicina,740.22,726.46,NaN,NaN,29.0
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,...,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Enfermagem,663.36,NaN,NaN,NaN,NaN
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,...,MzUxNTA2MTUwMzA4,Universidade Cidade de São Paulo - UNICID,UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...,1002328,Medicina,739.62,738.08,738.96,718.64,7.0
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,...,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Psicologia,651.00,652.22,NaN,NaN,5.0
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,...,MTIwMjAwNDAwNDAx,Faculdade Barão do Rio Branco - FAB,CAMPUS - RIO BRANCO - JARDIM EUROPA II - Jard...,658996,Medicina,758.32,723.94,734.92,711.26,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41442,Licenciatura,Curso a Distância,149.00,1.0,NaN,NaN,NaN,994312865605,Sociologia,Paraiso do Tocantins,...,MTcwMTAwNDE2MTA5,Universidade Paulista - UNIP,PARAISO DO TOCANTINS - Centro,9943,Sociologia,502.36,NaN,NaN,NaN,NaN
41443,Tecnológico,Curso a Distância,144.00,1.0,2.0,2.0,5.0,65868712869275,Marketing,Sao VIcente,...,MzUxNTA2MzUxMDA5,Faculdade de São VIcente - FSV,UNIDADE SEDE - Centro,658687,Marketing,533.34,450.00,450.00,450.00,3.0
41444,Tecnológico,Vespertino,139.00,1.0,NaN,NaN,NaN,1056445674232,Gestão de Recursos Humanos,Brasilia,...,NTMwMTAwMTAwMTA4,Centro Universitário Planalto do Distrito Fede...,DF03 - UNIDADE BRASIL CENTRAL - Taguatinga Nor...,1056445,Gestão de Recursos Humanos,580.76,NaN,NaN,NaN,NaN
41445,Bacharelado,Curso a Distância,139.00,1.0,NaN,NaN,NaN,96781210935,Serviço Social,Vitoria,...,MzIwMzAwOTA1MzA5,Universidade Paulista - UNIP,VITORIA I - Barro Vermelho,9678,Serviço Social,548.26,NaN,NaN,NaN,NaN
41446,Tecnológico,Curso a Distância,139.00,3.0,1.0,NaN,NaN,200467412868575,Gestão Ambiental,Santarem,...,MTUwMTAwMjA2ODA3,Universidade Paulista - UNIP,SANTARÉM - Fátima,2004674,Gestão Ambiental,605.32,573.70,NaN,NaN,4.0

// Traz a porcentagem da busca do curso por estado

In [17]:
pd.crosstab(df2.nome, df2.uf_busca, normalize= 'index')

uf_busca,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
nome,,,,,,,,,,,,,,,,,,,,,
Administração,0.004357,0.006899,0.008715,0.004357,0.070443,0.02687,0.023239,0.025054,0.035948,0.017792,...,0.092593,0.039942,0.012346,0.011983,0.002179,0.083515,0.042847,0.009804,0.223675,0.010167
Administração Pública,0.000000,0.000000,0.047619,0.000000,0.190476,0.00000,0.000000,0.000000,0.000000,0.047619,...,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.142857,0.000000,0.333333,0.000000
Administração de Empresas,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Administração de Recursos Humanos,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
Agroindústria,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Turismo e Hotelaria,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
Visagismo e Terapias Capilares,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
Viticultura e Enologia,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Zootecnia,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.090909,0.090909,...,0.000000,0.000000,0.000000,0.090909,0.000000,0.000000,0.090909,0.000000,0.181818,0.000000
Óptica e Optometria,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000

//Arredondando para 4 casas e deixando em porcentagem

In [18]:
pd.crosstab(df2.nome, df2.uf_busca, normalize= 'index').round(4)*100

uf_busca,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
nome,,,,,,,,,,,,,,,,,,,,,
Administração,0.44,0.69,0.87,0.44,7.04,2.69,2.32,2.51,3.59,1.78,...,9.26,3.99,1.23,1.20,0.22,8.35,4.28,0.98,22.37,1.02
Administração Pública,0.00,0.00,4.76,0.00,19.05,0.00,0.00,0.00,0.00,4.76,...,4.76,0.00,0.00,0.00,0.00,9.52,14.29,0.00,33.33,0.00
Administração de Empresas,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Administração de Recursos Humanos,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,100.00,0.00
Agroindústria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,100.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Turismo e Hotelaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00
Visagismo e Terapias Capilares,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,100.00,0.00
Viticultura e Enologia,0.00,0.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zootecnia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9.09,9.09,...,0.00,0.00,0.00,9.09,0.00,0.00,9.09,0.00,18.18,0.00
Óptica e Optometria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,100.00,0.00

In [20]:
df_agrupamento = df_prouni.groupby('curso_busca')
df_agrupamento

//Renorna o numero da linha onde aparece a informação

In [21]:
df_prouni.groupby('curso_busca').groups

{'Administração': [95, 96, 149, 177, 201, 203, 204, 220, 221, 246, 263, 361, 372, 418, 576, 633, 634, 635, 729, 730, 951, 1159, 1246, 1247, 1324, 1414, 1444, 1458, 1614, 1732, 1926, 1927, 1960, 1961, 2158, 2314, 2447, 2526, 2549, 2574, 2581, 2582, 2587, 2588, 2589, 2590, 2591, 2606, 2615, 2664, 2702, 2731, 2798, 2799, 2814, 2815, 2854, 2855, 2866, 2871, 2875, 2876, 2914, 2992, 2993, 3007, 3047, 3048, 3078, 3079, 3080, 3081, 3082, 3105, 3199, 3259, 3273, 3323, 3324, 3325, 3333, 3341, 3354, 3379, 3383, 3418, 3419, 3435, 3436, 3552, 3589, 3597, 3598, 3651, 3653, 3723, 3724, 3782, 3795, 3887, ...], 'Administração Pública': [9508, 10336, 10337, 17738, 23582, 23588, 23591, 23594, 25296, 25304, 25313, 25321, 25329, 25335, 25336, 28701, 29082, 29972, 29987, 33206, 34416], 'Administração de Empresas': [8622], 'Administração de Recursos Humanos': [15782, 16454, 18853, 19310, 19311, 19367, 20453], 'Agroindústria': [13874], 'Agronegócio': [5408, 5727, 9352, 10361, 11092, 11093, 11304, 11881, 11882, 12107, 12108, 13763, 13827, 13996, 14134, 14164, 15815, 15816, 15817, 16092, 16822, 16859, 16966, 17659, 17689, 20139, 20141, 20194, 20202, 20212, 20235, 20251, 20277, 20296, 20306, 20341, 20347, 20540, 20556, 20572, 20589, 20595, 20599, 20615, 20622, 20651, 20668, 20669, 20708, 20729, 20755, 20807, 20809, 20835, 20856, 20861, 20873, 20881, 20896, 21406, 21993, 22019, 22031, 22052, 22151, 24838, 25008, 25011, 25015, 25016, 25019, 25020, 25022, 25024, 25028, 25040, 25043, 25049, 25054, 25060, 25064, 25065, 25068, 25125, 25130, 25150, 25170, 25174, 25182, 25197, 25200, 25202, 25693, 25766, 25769, 26247, 26406, 26430, 26446, 28657, ...], 'Agronomia': [603, 604, 803, 843, 921, 1016, 1017, 1041, 1056, 1057, 1070, 1195, 1248, 1249, 1305, 1330, 1340, 1390, 1391, 1392, 1469, 1572, 1573, 1701, 1731, 1816, 1943, 1944, 1952, 1953, 2320, 2354, 2413, 2431, 2502, 2599, 2705, 2706, 2710, 2730, 2736, 2737, 2762, 2763, 2864, 2894, 3202, 3210, 3277, 3283, 3287, 3471, 3472, 3481, 3604, 4011, 4134, 4160, 4161, 4162, 4168, 4206, 4269, 4336, 4374, 4410, 4509, 4611, 4644, 4923, 4924, 4943, 4974, 4975, 5173, 5228, 5249, 5250, 5301, 5302, 5315, 5618, 5784, 5785, 5944, 5949, 5978, 6034, 6035, 6059, 6143, 6145, 6199, 6207, 6437, 6443, 6512, 6515, 6516, 6517, ...], 'Agropecuária': [6987], 'Alimentos': [7749, 14852, 15739, 15740], 'Análise e Desenvolvimento de Sistemas': [377, 1480, 1620, 2316, 2846, 2942, 2943, 3758, 3759, 3788, 4143, 4237, 4612, 4651, 4652, 4766, 4846, 4937, 5027, 5346, 5347, 5686, 5937, 6149, 6188, 6599, 6600, 6759, 6811, 7231, 7341, 7342, 7399, 7434, 7587, 7588, 7589, 7629, 7706, 7707, 7750, 7809, 7837, 7882, 7926, 8121, 8237, 8256, 8594, 8846, 8847, 8896, 9111, 9400, 9401, 9423, 9488, 9531, 9532, 9629, 9642, 9701, 9703, 9767, 9775, 9776, 9809, 9902, 9903, 10007, 10575, 10634, 10663, 10664, 10808, 10876, 10881, 11128, 11141, 11142, 11171, 11207, 11228, 11278, 11421, 11459, 11778, 11801, 11854, 11868, 11869, 11942, 11960, 12095, 12099, 12262, 12318, 12402, 12403, 12426, ...], 'Arqueologia': [8223], 'Arquitetura e Urbanismo': [141, 145, 175, 196, 244, 245, 274, 280, 281, 282, 286, 287, 288, 304, 329, 330, 348, 431, 443, 582, 615, 645, 646, 670, 671, 672, 689, 755, 756, 757, 765, 792, 793, 799, 800, 801, 802, 877, 878, 879, 880, 881, 906, 907, 908, 925, 926, 931, 956, 966, 970, 973, 990, 994, 995, 1000, 1018, 1045, 1062, 1063, 1115, 1134, 1135, 1136, 1140, 1184, 1185, 1186, 1198, 1199, 1200, 1220, 1273, 1318, 1319, 1337, 1338, 1339, 1347, 1358, 1359, 1389, 1398, 1399, 1435, 1466, 1485, 1486, 1487, 1494, 1515, 1634, 1635, 1657, 1705, 1713, 1720, 1721, 1729, 1745, ...], 'Artes': [18242], 'Artes Cênicas': [258, 12982], 'Artes VIsuais': [1241, 1242, 3195, 3915, 7616, 8087, 9005, 9103, 9442, 10854, 11837, 13188, 13189, 13254, 14787, 15654, 15974, 16237, 16268, 16291, 17796, 17934, 21674, 22111, 25334, 25562, 26066, 26188, 26222, 26244, 26284, 26285, 26299, 26358, 26375, 26424, 26443, 26562, 26592, 26603, 26628, 26651, 26685, 26797, 26830, 26849, 26867, 26875, 26884, 26926, 27014, 27037, 27085, 27128, 27178, 27246, 27288, 27361, 27388, 27406, 27476, 27483, 27516, 27586, 27639, 27656, 27708, 27721, 27734, 27769, 27811, 28676, 28725, 28757, 28789, 28821, 28854, 28951, 28952, 29349, 29351, 29406, 29428, 29464, 29471, 29978, 29994, 30179, 30239, 30306, 30327, 30328, 30336, 30338, 30343, 30539, 30553, 30779, 30799, 30834, ...], 'Audiovisual': [846, 847], 'Automação Industrial': [7586, 7847, 7848, 7899, 8398, 9421, 10508, 11800, 12425, 12799, 12804, 13480, 14013, 14031, 14186, 14431, 14507, 14863, 15615, 16631, 16664, 16794, 16921, 17162, 17163, 17164, 17227, 17448, 19019], 'Banco de Dados': [2263, 2333, 3961, 5026, 6730, 9464, 16106, 16480, 16535, 16536, 18110, 18877, 18878, 18879, 19337, 35275, 35293, 35308, 35327, 35360, 35386, 35404, 35449, 35501, 35519, 35536, 35547, 35572, 35590, 35623, 35650, 35664, 35690, 35725, 35856, 35857, 35858, 35859, 35860, 35861, 35884, 35904, 35921, 35943, 35964, 36077, 36078, 36079, 36080, 36118, 36132, 36151, 36169, 36183, 36245, 36246, 36247, 36248], 'Biblioteconomia': [1728, 13836, 16144, 21880, 21881, 21882, 21883, 21884, 21885, 21886, 21887, 21888, 21889, 21890, 21891, 21892, 21893, 21894, 21895, 21896, 21897, 21898, 21899, 21900, 21901, 21902, 21903, 21905, 21906, 21907, 21908, 21909, 21910, 21911, 21912, 21913, 21914, 21915, 21916, 21917, 21918, 21958, 25295, 25303, 25312, 25320, 25328, 25339, 25340], 'Biocombustíveis': [13890, 13891], 'Biologia': [10149, 16403, 17808, 21904, 26560, 26573, 26597, 26622, 26633, 26641, 26677, 26877, 26911, 26984, 27074, 27103, 27170, 27192, 27199, 27214, 27231, 27281, 27292, 27356, 27386, 27434, 27504, 27618, 27626, 27682, 27723, 27800, 33359], 'Biomedicina': [293, 302, 335, 531, 533, 589, 590, 591, 657, 681, 696, 700, 703, 704, 905, 912, 1023, 1029, 1042, 1096, 1099, 1100, 1146, 1352, 1473, 1552, 1553, 1595, 1609, 1658, 1668, 1682, 1683, 1684, 1754, 1755, 1860, 1862, 1895, 1982, 1983, 2004, 2017, 2087, 2127, 2128, 2177, 2178, 2179, 2180, 2181, 2235, 2236, 2285, 2286, 2289, 2374, 2375, 2376, 2377, 2444, 2449, 2543, 2545, 2546, 2610, 2649, 2650, 2654, 2749, 2800, 2829, 2830, 2976, 2977, 3039, 3040, 3049, 3050, 3062, 3066, 3067, 3127, 3243, 3371, 3422, 3423, 3433, 3457, 3460, 3461, 3533, 3547, 3613, 3629, 3632, 3633, 3682, 3694, 3695, ...], 'Biotecnologia': [686, 17728, 17729], 'Cinema e Audiovisual': [1375, 1376, 2427, 2428, 2537, 2538, 6312, 6545, 8358], 'Ciência Econômica': [4278, 14519, 18763, 18764, 21293, 21294, 21299, 21301, 21304], 'Ciência Política': [9511, 10814, 18535, 25301, 25309, 25318, 25326, 25349, 25350, 28883, 32162, 32164, 32167, 32171, 32173, 32178, 32183, 32191, 32193, 32197, 32199, 32201, 32204, 32206, 32208, 32211, 32214, 32215, 32218, 32224, 32227, 32229, 32230, 32234, 32235, 32238, 32243, 32246, 32252, 32254, 32258, 32261, 32265, 32269, 32272, 32279, 32282, 32287, 32289, 32294, 32297, 32300, 32307, 32310, 32313, 32319, 32323, 32327, 32333, 32334, 32338, 32343, 32346, 32355, 32356, 32357, 32358, 32366, 32380, 32382, 32387, 32390, 32394, 32398, 32403, 32404, 32405, 32409, 32410, 32412, 32414, 32416, 32419, 32422, 32424, 32427, 32428, 32429, 32430, 32434, 32439, 32441, 32444, 32446, 32449, 32451, 32454, 32455, 32458, 32461, ...], 'Ciência da Computação': [171, 386, 745, 979, 1003, 1122, 1145, 1208, 1325, 1380, 1413, 1490, 1525, 1526, 1567, 1568, 1569, 1570, 1600, 1601, 1670, 1962, 2090, 2291, 2551, 2648, 2655, 2656, 2692, 2693, 2994, 3206, 3272, 3489, 3492, 3505, 3506, 3588, 3709, 3774, 3975, 3976, 4025, 4148, 4171, 4260, 4322, 4452, 4593, 4671, 4672, 4727, 4728, 4758, 4854, 4906, 4925, 5033, 5048, 5675, 5985, 6345, 6576, 6694, 6725, 6804, 6860, 6952, 7239, 7244, 7395, 7542, 7650, 7825, 7890, 7929, 8108, 8227, 8639, 8664, 8849, 8852, 8854, 9002, 9042, 9127, 9128, 9226, 9261, 9314, 9344, 9351, 9446, 9467, 9526, 9527, 9604, 9612, 9665, 9675, ...], 'Ciências': [14984], 'Ciências Aeronáuticas': [273, 647, 1355, 1751, 2828, 4655, 5562, 5563, 5564, 5565, 5566, 5567, 5568, 5669], 'Ciências Atuariais': [342, 11793], 'Ciências Biológicas': [185, 186, 625, 640, 899, 922, 1075, 1271, 1737, 1968, 1969, 2059, 2212, 2349, 2350, 2623, 2687, 2688, 2689, 2983, 3110, 3111, 3122, 3123, 3194, 3332, 3475, 3683, 4583, 4584, 4589, 4590, 4591, 4592, 4752, 4753, 5207, 5208, 5308, 5309, 5445, 5508, 5759, 5847, 6274, 6469, 6476, 6554, 6894, 7083, 7197, 7326, 7327, 8159, 8285, 8310, 8321, 8322, 8323, 8343, 8435, 8694, 8695, 8888, 9037, 9102, 9151, 9152, 9171, 9172, 9203, 9273, 9406, 9431, 9441, 9497, 9580, 9581, 10080, 10081, 10210, 10235, 10266, 10367, 10382, 10417, 10766, 10852, 10853, 10884, 10904, 10905, 11131, 11240, 11269, 11299, 11430, 11445, 11570, 11571, ...], 'Ciências Biológicas - Modalidade Médica': [3488], 'Ciências Contábeis': [127, 264, 369, 636, 637, 731, 758, 939, 952, 1446, 1460, 1712, 1910, 2159, 2351, 2550, 2640, 2641, 2642, 2643, 2665, 2734, 2874, 3108, 3109, 3260, 3339, 3660, 3725, 3789, 3982, 3983, 3994, 4014, 4075, 4078, 4083, 4131, 4154, 4213, 4214, 4220, 4221, 4228, 4229, 4258, 4259, 4386, 4535, 4581, 4702, 4703, 4736, 4739, 4745, 4746, 4771, 4772, 4784, 4811, 4898, 4909, 4929, 4958, 4959, 4960, 4961, 4965, 4966, 4967, 5096, 5097, 5134, 5214, 5384, 5400, 5401, 5402, 5403, 5406, 5496, 5497, 5518, 5601, 5745, 5806, 5853, 5881, 6146, 6147, 6247, 6271, 6378, 6379, 6433, 6434, 6435, 6436, 6458, 6607, ...], 'Ciências Econômicas': [152, 184, 194, 195, 354, 355, 581, 710, 711, 732, 733, 1461, 2644, 2645, 2646, 2647, 3348, 3349, 3995, 4017, 4041, 4109, 4222, 4223, 4257, 4337, 4418, 4582, 4716, 4917, 4957, 5050, 5051, 5135, 5215, 5382, 5383, 5398, 5399, 5617, 6223, 6616, 6994, 7050, 7451, 7674, 7844, 7917, 8146, 8199, 8796, 8986, 9564, 9565, 9987, 10046, 10165, 11010, 11011, 11232, 11389, 11784, 11792, 12423, 12621, 12933, 13394, 14042, 14483, 14828, 14916, 15108, 15279, 15640, 16024, 16033, 16034, 16426, 16831, 16881, 17950, 18378, 18522, 19297, 20608, 20617, 20621, 20635, 20695, 20696, 20704, 20706, 20717, 20727, 20746, 20767, 20772, 20778, 20783, 20787, ...], 'Ciências Sociais': [249, 250, 373, 374, 2630, 3355, 3356, 7855, 7856, 8647, 13870, 14786, 18392, 19610, 26472, 26473, 35944, 35965, 35989, 36081, 36082, 36102, 39034, 39035, 39036, 39037, 39038, 39039, 39045, 39049, 39053, 39054, 39058, 39059, 39062, 39066, 39067, 39068, 39072, 39073, 39074, 39075, 39083, 39090, 39091, 39094, 39098, 39099, 39103, 39105, 39109, 39112, 39120, 39123, 39137, 39138, 39139, 39140, 39141, 39142, 39146, 39153], 'Ciências da Computação': [9088, 12562, 14050, 14257, 15697, 15698, 17487, 17665], 'Ciências da Religião': [30066], 'Computação': [15511, 26650, 26795, 26829, 26935, 27052, 27177, 27287, 27297, 27405, 27444, 27462, 27475, 27637, 27655, 27707, 27733, 27768], 'Comunicação Empresarial': [18348, 19448, 19455, 20033, 20048, 21165, 21376], 'Comunicação Institucional': [14411, 16072, 16524, 16931, 17769, 17770, 17780, 20109, 20452, 21195, 21348, 21876, 21877], 'Comunicação Social': [1929, 1930, 1931, 5360, 7205, 8101, 8102, 8850, 9272, 11412, 12968, 13419, 14002, 14362, 15308, 16054, 16111, 18171, 18253, 18284, 18286, 18287, 18289, 18290, 18291, 18293, 18303, 18306, 18309, 18313, 18314, 18315, 18322, 18325, 18610, 18611, 18613, 18673, 18747, 18920, 19291, 19304, 19436, 19437, 26475], 'Comunicação Social  - Radialismo': [8780, 8781], 'Comunicação Social - Cinema': [228, 384, 385], 'Comunicação Social - Cinema e Audiovisual': [2119], 'Comunicação Social - Cinema e Mídias Digitais': [4189, 4190], 'Comunicação Social - Jornalismo': [226, 298, 1988, 2117, 2118, 2332, 2600, 2697, 2700, 3029, 3200, 3201, 3312, 4191, 4192, 4353, 4354, 4614, 5132, 5239, 5314, 5388, 5708, 6375, 6430, 6745, 7177, 7224, 8469, 8782, 8783, 8983, 9355, 9570, 9928, 10111, 10184, 10284, 10384, 10872, 11262, 11499, 11500, 11516, 11755, 11819, 11839, 12282, 12603, 12713, 13047, 13055, 13383, 13773, 14223, 14312, 14480, 15375, 15822, 17245, 17913, 18643], 'Comunicação Social - Publicidade e Propaganda': [169, 183, 227, 299, 300, 350, 477, 478, 568, 569, 779, 1105, 1201, 1223, 1224, 1351, 1439, 1577, 1739, 1740, 1838, 1839, 1989, 2058, 2113, 2130, 2131, 2132, 2133, 2174, 2269, 2303, 2330, 2331, 2601, 2612, 2698, 2701, 2748, 2784, 2790, 2794, 2879, 2930, 2968, 3030, 3274, 3313, 3387, 3420, 3665, 3666, 3732, 3816, 3993, 4000, 4001, 4003, 4128, 4129, 4194, 4195, 4208, 4209, 4219, 4355, 4356, 5092, 5133, 5154, 5240, 5363, 5434, 5454, 5561, 5709, 5833, 5872, 5932, 5999, 6000, 6082, 6254, 6291, 6347, 6386, 6387, 6568, 6754, 6891, 7113, 7202, 7323, 7369, 7460, 7539, 7642, 8103, 8104, 8149, ...], 'Comunicação Social - Radialismo (Rádio e Tv)': [1239, 1240], 'Comunicação Social - Radio e Televisão': [2793, 10871, 12281, 13046], 'Comunicação Social - Relações Públicas': [8099, 8100, 21279], 'Comunicação Social com Habilitação em Publicidade e Propaganda': [11920], 'Comunicação e Ilustração Digital': [18347, 19453, 19525, 20032, 20049, 21164, 21375], 'Comunicação e Multimeios': [352], 'Comunicação para Web': [19447, 19454, 20031, 20047, 21166], 'Comércio Exterior': [3586, 3587, 3661, 4963, 5137, 5138, 6431, 6432, 6618, 6782, 7795, 7803, 8147, 8632, 8845, 9766, 9790, 9791, 9792, 10746, 11887, 12181, 12191, 12215, 12381, 12382, 12857, 13114, 13443, 13795, 13830, 13970, 14045, 14135, 14412, 14508, 14536, 14938, 15286, 15570, 15692, 15802, 16073, 16375, 16481, 16525, 16568, 16641, 16653, 16665, 16672, 16683, 16860, 16922, 16950, 16983, 16992, 17038, 17305, 17308, 17352, 17451, 17479, 17771, 17772, 17931, 18275, 18379, 18666, 18710, 18711, 18722, 18826, 18880, 18913, 19029, 19030, 19033, 19338, 19339, 19340, 19352, 19353, 19375, 19396, 19402, 19466, 19467, 19551, 19561, 19866, 20050, 20106, 20114, 20115, 20116, 20457, 20535, 20929, 21031, ...], 'Construção Naval': [4307, 12025, 12026], 'Construção de Edifícios': [7580, 7843, 8917, 8918, 9870, 9871, 10720, 10721, 11467, 11885, 11886, 11956, 12151, 12748, 16135, 16689, 18183, 18225, 18269, 18598, 18599, 18899, 19254, 21282], 'Controle de Obras': [9869, 19253], 'Dança': [6410, 6411, 7615, 13253], 'Defesa Cibernética': [1479, 3757, 5597, 5625, 5626, 8895, 10719], 'Desenho Industrial': [209, 210, 211, 212], 'Desenvolvimento de Sistemas': [14004], 'Design': [297, 383, 448, 632, 641, 709, 738, 739, 1687, 1795, 1796, 1873, 1874, 1875, 1876, 2109, 2248, 2264, 2391, 2523, 2524, 2575, 2576, 2653, 3001, 3002, 3350, 3357, 3437, 3438, 3863, 3905, 4140, 4283, 4284, 4294, 4295, 4595, 4606, 4726, 5058, 5130, 5800, 6393, 6456, 6762, 7301, 7459, 7579, 8188, 8189, 8284, 8287, 8288, 8449, 8981, 9119, 9342, 9528, 9978, 10043, 10172, 10255, 10447, 11006, 11007, 11484, 11485, 11486, 11487, 11488, 12322, 12323, 12780, 12883, 13281, 13940, 14902, 16018, 16104, 16105, 16556, 17905, 17906, 17907, 17992, 18336], 'Design Digital': [1483, 2253], 'Design Gráfico': [1152, 1153, 1377, 2110, 2713, 2741, 3528, 3686, 3745, 3906, 4289, 4290, 4298, 4457, 4458, 4763, 5666, 6445, 6583, 6736, 6737, 6878, 7181, 7182, 7433, 8136, 8222, 8396, 8397, 8539, 8728, 8843, 8844, 9266, 9287, 9288, 9480, 9633, 10006, 10269, 10270, 10317, 10903, 10971, 10978, 11302, 11952, 12145, 12420, 12734, 12735, 13083, 13140, 13241, 13313, 13314, 14030, 14033, 14104, 14165, 14185, 14376, 14384, 14392, 14966, 15045, 15293, 15294, 15371, 15664, 15675, 15676, 15677, 16125, 16126, 16199, 16361, 16367, 16565, 16600, 16612, 16613, 16622, 16663, 16809, 16821, 16930, 16982, 17010, 17059, 17160, 17161, 17259, 17674, 17711, 17911, 17912, 18109, 18113, 18194, ...], 'Design de Animação': [10900], 'Design de Games': [596], 'Design de Interiores': [1561, 1877, 1878, 2939, 2940, 2941, 3802, 4285, 4286, 4296, 4297, 4534, 4762, 5067, 5216, 5321, 5327, 5328, 6546, 6642, 6703, 6704, 6735, 6979, 7378, 7743, 7936, 8113, 8134, 8394, 8395, 8742, 8999, 9000, 9286, 9327, 9756, 9867, 9868, 10316, 10357, 10408, 10488, 10816, 10817, 11132, 11195, 11637, 11694, 11748, 11799, 11951, 12036, 12067, 12245, 12246, 12345, 12393, 12429, 12439, 12645, 12661, 12732, 12733, 13423, 13424, 13756, 13774, 13843, 13960, 13998, 14184, 14214, 14215, 14298, 14299, 14305, 14399, 14878, 14971, 14972, 15025, 15050, 15051, 15177, 15209, 15282, 15289, 15657, 15695, 15714, 15763, 15764, 15852, 15985, 16123, 16205, 16206, 16596, 16623, ...], 'Design de Moda': [1371, 2792, 3358, 3359, 3743, 4287, 4288, 4680, 5119, 5191, 5192, 5739, 6087, 6701, 6702, 6955, 6980, 7794, 7802, 8135, 8162, 8349, 8404, 9011, 9737, 10245, 10589, 10590, 10670, 10672, 10771, 10772, 10820, 10882, 10990, 10991, 11081, 11647, 11742, 12053, 12180, 12203, 12336, 12385, 12411, 12922, 13368, 13458, 14118, 15374, 15898, 16004, 16695, 16808, 16836, 16929, 17047, 17099, 17333, 17359, 17360, 17362, 17363, 17366, 17369, 17372, 17376, 17378, 17379, 17382, 17383, 17384, 17386, 17387, 17388, 17389, 17393, 17394, 17397, 17399, 17404, 17409, 17410, 17417, 17419, 17423, 17425, 17431, 17433, 18373], 'Design de Moda - Estilismo': [1265], 'Design de Moda - Modelagem': [1762], 'Design de Produto': [3744, 5539, 7808, 7863, 9478, 10653, 10654, 11082, 17008, 17357, 17368, 17375, 17380, 17381, 17390, 17395, 17405, 17407, 17411, 17415, 17422, 17424, 17427, 17429, 17903, 17904, 18125, 18580, 18581], 'Digital Influencer': [18777], 'Direito': [43, 44, 182, 213, 225, 235, 236, 237, 267, 268, 337, 510, 668, 669, 716, 717, 746, 747, 893, 976, 977, 1009, 1010, 1033, 1034, 1162, 1163, 1164, 1204, 1205, 1207, 1245, 1272, 1326, 1327, 1332, 1333, 1335, 1345, 1346, 1378, 1379, 1382, 1385, 1386, 1387, 1388, 1470, 1471, 1495, 1496, 1497, 1504, 1505, 1507, 1518, 1519, 1531, 1532, 1540, 1541, 1546, 1547, 1557, 1558, 1559, 1597, 1602, 1603, 1610, 1622, 1625, 1626, 1628, 1629, 1647, 1648, 1649, 1650, 1651, 1660, 1661, 1676, 1679, 1680, 1690, 1698, 1699, 1714, 1723, 1765, 1766, 1767, 1768, 1779, 1780, 1781, 1782, 1783, 1790, ...], 'Educação Artística - Música': [4114], 'Educação Especial': [9611, 18983, 26064, 26095, 26146, 26199, 26279, 26297, 26313, 26325, 26343, 26356, 26369, 26389, 26399, 26422, 26466, 28668, 28695, 28715, 28723, 29976, 32703, 32716, 32744, 32823, 37886], 'Educação Física': [14, 15, 153, 946, 947, 1165, 1278, 1279, 1280, 1281, 1357, 1362, 1417, 1445, 1537, 1617, 1637, 1638, 1774, 1775, 1911, 1912, 1913, 1914, 2071, 2073, 2074, 2106, 2111, 2112, 2396, 2397, 2613, 2888, 2934, 2935, 2936, 2937, 3125, 3126, 3193, 3196, 3207, 3366, 3367, 3496, 3497, 3498, 3499, 3502, 3503, 3504, 3507, 3508, 3509, 3572, 3579, 3580, 3667, 3823, 3978, 3979, 3980, 3981, 3996, 3997, 4033, 4036, 4037, 4152, 4153, 4253, 4254, 4263, 4264, 4357, 4358, 4399, 4400, 4406, 4407, 4408, 4417, 4419, 4420, 4579, 4580, 4588, 4620, 4621, 4648, 4748, 4749, 4750, 4862, 4971, 5037, 5038, 5069, 5070, ...], 'Eletrônica Industrial': [8226, 8599, 9866, 10875], 'Embelezamento e Imagem Pessoal': [21493, 21843, 21845, 21860, 22057, 22060, 22064, 22067, 22225, 22227, 22245, 22249, 22250, 23233, 23252, 23257, 23264, 24962, 24973, 25027, 25036, 25062, 25104, 25110, 25115, 25118, 25436, 25634, 26604, 26605, 26621, 26639, 26860, 26927, 26968, 26981, 27155, 27311, 27335, 27385, 29326, 29375, 29392, 29399, 29423, 29456, 29536, 30204, 30219, 30241, 30288, 30372, 30563, 30654, 30859, 34005, 34075, 34180, 34181, 34236, 34274, 34296, 34980, 34985, 35010, 35011, 35012, 35019, 35036, 35082, 35089, 35131, 35143, 35219, 36886, 36924, 36949, 36951, 36954, 36956, 36971, 37021, 37055, 37540, 37598, 37638, 39590, 39833, 40029, 40165, 40167, 40200, 40208, 40215, 40238, 40269, 40276, 40308, 40329, 40337, ...], 'Enfermagem': [1, 81, 82, 270, 370, 679, 680, 697, 702, 735, 744, 808, 809, 924, 1022, 1027, 1028, 1039, 1084, 1110, 1111, 1120, 1127, 1166, 1212, 1243, 1282, 1283, 1285, 1313, 1329, 1433, 1434, 1472, 1488, 1491, 1492, 1618, 1619, 1654, 1655, 1665, 1666, 1677, 1678, 1722, 1764, 1802, 1805, 1806, 1811, 1812, 1844, 1899, 1917, 1918, 1932, 1956, 1957, 1981, 1998, 2047, 2075, 2077, 2085, 2136, 2142, 2173, 2201, 2202, 2209, 2216, 2242, 2243, 2259, 2260, 2283, 2284, 2287, 2288, 2292, 2310, 2319, 2365, 2366, 2423, 2430, 2500, 2501, 2516, 2517, 2518, 2519, 2520, 2521, 2535, 2579, 2602, 2732, 2733, ...], 'Enfermagem e Obstetrícia': [52

//Conta a quantidade de registros

In [22]:
df_prouni.groupby('curso_busca').size()

curso_busca
Administração                        2754
Administração Pública                  21
Administração de Empresas               1
Administração de Recursos Humanos       7
Agroindústria                           1
                                     ...
Turismo e Hotelaria                     1
Visagismo e Terapias Capilares          2
Viticultura e Enologia                  2
Zootecnia                              11
Óptica e Optometria                     2
Length: 296, dtype: int64

//get_group filtra aquele determinado grupo

In [23]:
df_prouni.groupby('curso_busca').get_group('Administração')

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,...,cidade_filtro,universidade_nome,campus_nome,campus_external_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas,total_bolsas
95,Bacharelado,Matutino,6552.52,1.0,2.0,NaN,NaN,1004316487721,Administração,Curitiba,...,NDExMDAzNzA2OTAy,Faculdade Dom Bosco - FDB,MARUMBY - Lindóia,1004316,Administração,558.22,592.68,NaN,NaN,3.0
96,Bacharelado,Noturno,6552.52,1.0,2.0,NaN,NaN,1004316487723,Administração,Curitiba,...,NDExMDAzNzA2OTAy,Faculdade Dom Bosco - FDB,MARUMBY - Lindóia,1004316,Administração,559.12,567.38,NaN,NaN,3.0
149,Bacharelado,Noturno,4482.00,0.0,1.0,NaN,4.0,6590711181133,Administração,Cafelandia,...,NDEwNjAyMzAzNDUz,Faculdade de Cafelândia - FAC,UNIDADE SEDE - Parque São Paulo,659071,Administração,588.10,NaN,550.08,NaN,1.0
177,Bacharelado,Integral,3851.00,1.0,1.0,NaN,NaN,658483207514,Administração,Campinas,...,MzUwNzAzMjA5NTAy,Faculdade de Administração de Empresas - FACAMP,CAMPUS - CAMPINAS - BARÃO GERALDO - Barão Ger...,658483,Administração,537.02,602.54,NaN,NaN,2.0
201,Bacharelado,Integral,3621.57,1.0,3.0,NaN,NaN,104909950007224,Administração,Porto Alegre,...,NDMwNTAyNjE0OTAy,Universidade do Vale do Rio dos Sinos - UNISINOS,UNISINOS PORTO ALEGRE - Três Figueiras,1049099,Administração,597.96,601.52,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41094,Bacharelado,Curso a Distância,169.00,0.0,1.0,NaN,NaN,107306550013345,Administração,Aracatuba,...,MzUwMzAxNzAyODA0,Centro Universitário Planalto do Distrito Fede...,ARAÇATUBA/SP - Vila Estádio,1073065,Administração,489.48,NaN,NaN,NaN,1.0
41095,Bacharelado,Curso a Distância,169.00,0.0,1.0,NaN,NaN,107308250013345,Administração,Catanduva,...,MzUwMTAwNTExMTAy,Centro Universitário Planalto do Distrito Fede...,CATANDUVA/SP - Centro,1073082,Administração,450.00,NaN,NaN,NaN,1.0
41097,Bacharelado,Curso a Distância,169.00,0.0,1.0,NaN,NaN,107308850013345,Administração,Guaratingueta,...,MzUxMzA1MTE4NDA0,Centro Universitário Planalto do Distrito Fede...,GUARATINGUETÁ/SP - Campo do Galvão,1073088,Administração,566.96,NaN,NaN,NaN,1.0
41101,Bacharelado,Curso a Distância,169.00,0.0,1.0,NaN,NaN,107313050013345,Administração,Sao Jose do Rio Preto,...,MzUwMTAwNDQ5ODA1,Centro Universitário Planalto do Distrito Fede...,SÃO JOSÉ DO RIO PRETO/SP - Vila Sinibaldi,1073130,Administração,530.12,NaN,NaN,NaN,1.0
41103,Bacharelado,Curso a Distância,169.00,0.0,1.0,NaN,NaN,107314150013345,Administração,Taubate,...,MzUxMzA1MDU0MTAy,Centro Universitário Planalto do Distrito Fede...,TAUBATÉ/SP - Jardim das Nações,1073141,Administração,552.00,NaN,NaN,NaN,1.0

In [24]:
df_prouni.groupby('curso_busca').mean()

<ipython-input-24-65968f74ef44>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_prouni.groupby('curso_busca').mean()

,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,campus_external_id,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas,total_bolsas
curso_busca,,,,,,,,,,,,
Administração,542.997491,1.774038,2.876598,2.096491,11.916955,2.998479e+13,6.864286e+05,575.236670,554.266651,533.483580,510.981995,4.826570
Administração Pública,390.464286,1.809524,3.588235,2.000000,1.333333,1.047483e+14,1.109614e+06,529.886667,505.745000,539.873333,521.060000,5.588235
Administração de Empresas,919.000000,2.000000,2.000000,2.000000,2.000000,1.338591e+13,1.338590e+05,638.420000,610.720000,590.140000,581.260000,4.000000
Administração de Recursos Humanos,468.571429,2.285714,4.714286,NaN,NaN,3.614423e+11,2.966261e+05,559.077143,545.100000,NaN,NaN,7.000000
Agroindústria,650.750000,1.000000,1.000000,1.000000,3.000000,6.587241e+13,6.587240e+05,570.520000,524.800000,465.540000,484.920000,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
Turismo e Hotelaria,1192.400000,0.000000,15.000000,NaN,NaN,2.983934e+07,2.980000e+02,559.120000,NaN,NaN,NaN,15.000000
Visagismo e Terapias Capilares,1094.500000,2.500000,4.500000,NaN,NaN,2.503107e+10,2.503000e+03,586.300000,570.230000,NaN,NaN,7.000000
Viticultura e Enologia,840.000000,2.000000,NaN,4.000000,1.000000,1.057393e+14,1.057393e+06,512.300000,NaN,467.430000,450.000000,NaN
Zootecnia,1124.844545,1.636364,2.555556,3.666667,6.333333,7.041611e+12,5.802758e+05,602.403636,592.203333,540.286667,526.606667,4.222222
Óptica e Optometria,990.000000,0.500000,2.500000,NaN,NaN,2.580271e+10,2.580200e+04,620.830000,553.360000,NaN,NaN,3.000000

//Soma do total de bolsas do curso por estado

In [30]:
df2.groupby(['curso_busca', 'uf_busca'])['total_bolsas'].sum()

df3 = (df2.groupby(['curso_busca', 'uf_busca'])['total_bolsas'].sum()).copy()
df3

curso_busca          uf_busca
Administração        AC           14.0
                     AL           82.0
                     AM          100.0
                     AP           43.0
                     BA          403.0
                                 ...
Zootecnia            PA            4.0
                     RO           11.0
                     SC            2.0
                     SP           13.0
Óptica e Optometria  SP            6.0
Name: total_bolsas, Length: 2715, dtype: float64

//**CONCATENAÇÃO**

In [38]:
clientes = pd.read_excel('/content/CLIENTES.xlsx')
clientes

   ID       NOME SOBRENOME
0   1        ANA  PATRICIA
1   2  FRANCIELE  OLIVEIRA
2   3   FERNANDA    TORRES
3   4   CRISTINA    SOARES
4   5      MARIA   ANTONIA
5   6    GUSTAVO  FERREIRA
6   7   FERNANDO    PESSOA

In [33]:
produtos = pd.read_excel('/content/PRODUTO.xlsx')
produtos

   ID_CLIENTE         PRODUTO  QUANTIDADE  PRECO_UNIT
0           4          ESCOVA           4        2.99
1           2          XAMPOO           2       17.99
2           6        SABONETE           3        2.75
3           7     DESODORANTE           1       11.79
4           1   CONDICIONADOR           5       19.99
5           2      GEL FACIAL           1       15.87
6           4      ESFOLIANTE           2       13.99
7           3  PASTA DE DENTE           7        6.99
8           2      HIDRATANTE           4       22.39

In [43]:
clientes['nome_completo'] = clientes.NOME + ' ' + clientes.SOBRENOME
df_clientes = clientes.copy()
df_clientes

   ID       NOME SOBRENOME       nome_completo
0   1        ANA  PATRICIA        ANA PATRICIA
1   2  FRANCIELE  OLIVEIRA  FRANCIELE OLIVEIRA
2   3   FERNANDA    TORRES     FERNANDA TORRES
3   4   CRISTINA    SOARES     CRISTINA SOARES
4   5      MARIA   ANTONIA       MARIA ANTONIA
5   6    GUSTAVO  FERREIRA    GUSTAVO FERREIRA
6   7   FERNANDO    PESSOA     FERNANDO PESSOA

In [42]:
produtos['TOTAL_VENDA'] = produtos.QUANTIDADE * produtos.PRECO_UNIT
df_produtos = produtos.copy()
df_produtos

   ID_CLIENTE         PRODUTO  QUANTIDADE  PRECO_UNIT  TOTAL_VENDA
0           4          ESCOVA           4        2.99        11.96
1           2          XAMPOO           2       17.99        35.98
2           6        SABONETE           3        2.75         8.25
3           7     DESODORANTE           1       11.79        11.79
4           1   CONDICIONADOR           5       19.99        99.95
5           2      GEL FACIAL           1       15.87        15.87
6           4      ESFOLIANTE           2       13.99        27.98
7           3  PASTA DE DENTE           7        6.99        48.93
8           2      HIDRATANTE           4       22.39        89.56

In [45]:
clientes['nome_completo2'] = clientes[['NOME', 'SOBRENOME']].apply(' ' .join, axis=1)
clientes

   ID       NOME SOBRENOME       nome_completo      nome_completo2
0   1        ANA  PATRICIA        ANA PATRICIA        ANA PATRICIA
1   2  FRANCIELE  OLIVEIRA  FRANCIELE OLIVEIRA  FRANCIELE OLIVEIRA
2   3   FERNANDA    TORRES     FERNANDA TORRES     FERNANDA TORRES
3   4   CRISTINA    SOARES     CRISTINA SOARES     CRISTINA SOARES
4   5      MARIA   ANTONIA       MARIA ANTONIA       MARIA ANTONIA
5   6    GUSTAVO  FERREIRA    GUSTAVO FERREIRA    GUSTAVO FERREIRA
6   7   FERNANDO    PESSOA     FERNANDO PESSOA     FERNANDO PESSOA

//Função merge com o parâmetro inner: faz a junção pelas chaves

In [62]:
df_merge = pd.merge(df_clientes, df_produtos, how= 'inner', on='ID')
df_merge

,ID,NOME,SOBRENOME,nome_completo,PRODUTO,QUANTIDADE,PRECO_UNIT,TOTAL_VENDA
0,1,ANA,PATRICIA,ANA PATRICIA,CONDICIONADOR,5,19.99,99.95
1,2,FRANCIELE,OLIVEIRA,FRANCIELE OLIVEIRA,XAMPOO,2,17.99,35.98
2,2,FRANCIELE,OLIVEIRA,FRANCIELE OLIVEIRA,GEL FACIAL,1,15.87,15.87
3,2,FRANCIELE,OLIVEIRA,FRANCIELE OLIVEIRA,HIDRATANTE,4,22.39,89.56
4,3,FERNANDA,TORRES,FERNANDA TORRES,PASTA DE DENTE,7,6.99,48.93
5,4,CRISTINA,SOARES,CRISTINA SOARES,ESCOVA,4,2.99,11.96
6,4,CRISTINA,SOARES,CRISTINA SOARES,ESFOLIANTE,2,13.99,27.98
7,6,GUSTAVO,FERREIRA,GUSTAVO FERREIRA,SABONETE,3,2.75,8.25
8,7,FERNANDO,PESSOA,FERNANDO PESSOA,DESODORANTE,1,11.79,11.79

In [49]:
produtos['ID'] = produtos.ID_CLIENTE
produtos

   ID_CLIENTE         PRODUTO  QUANTIDADE  PRECO_UNIT  TOTAL_VENDA  ID
0           4          ESCOVA           4        2.99        11.96   4
1           2          XAMPOO           2       17.99        35.98   2
2           6        SABONETE           3        2.75         8.25   6
3           7     DESODORANTE           1       11.79        11.79   7
4           1   CONDICIONADOR           5       19.99        99.95   1
5           2      GEL FACIAL           1       15.87        15.87   2
6           4      ESFOLIANTE           2       13.99        27.98   4
7           3  PASTA DE DENTE           7        6.99        48.93   3
8           2      HIDRATANTE           4       22.39        89.56   2

In [56]:
df_produtos = produtos[['ID','PRODUTO', 'QUANTIDADE', 'PRECO_UNIT', 'TOTAL_VENDA', ]]
df_produtos

   ID         PRODUTO  QUANTIDADE  PRECO_UNIT  TOTAL_VENDA
0   4          ESCOVA           4        2.99        11.96
1   2          XAMPOO           2       17.99        35.98
2   6        SABONETE           3        2.75         8.25
3   7     DESODORANTE           1       11.79        11.79
4   1   CONDICIONADOR           5       19.99        99.95
5   2      GEL FACIAL           1       15.87        15.87
6   4      ESFOLIANTE           2       13.99        27.98
7   3  PASTA DE DENTE           7        6.99        48.93
8   2      HIDRATANTE           4       22.39        89.56

//Função merge com o parâmetro left: faz a junção das tabelas pelas linhas da coluna à esquerda

In [ ]:
df_merge = pd.merge(df_clientes, df_produtos, how= 'left', on='ID')
df_merge

//Função merge com o parâmetro right: faz a junção das tabelas pelas linhas da coluna à direita

In [64]:
df_merge = pd.merge(df_clientes, df_produtos, how= 'right', on='ID')
df_merge

,ID,NOME,SOBRENOME,nome_completo,PRODUTO,QUANTIDADE,PRECO_UNIT,TOTAL_VENDA
0,4,CRISTINA,SOARES,CRISTINA SOARES,ESCOVA,4,2.99,11.96
1,2,FRANCIELE,OLIVEIRA,FRANCIELE OLIVEIRA,XAMPOO,2,17.99,35.98
2,6,GUSTAVO,FERREIRA,GUSTAVO FERREIRA,SABONETE,3,2.75,8.25
3,7,FERNANDO,PESSOA,FERNANDO PESSOA,DESODORANTE,1,11.79,11.79
4,1,ANA,PATRICIA,ANA PATRICIA,CONDICIONADOR,5,19.99,99.95
5,2,FRANCIELE,OLIVEIRA,FRANCIELE OLIVEIRA,GEL FACIAL,1,15.87,15.87
6,4,CRISTINA,SOARES,CRISTINA SOARES,ESFOLIANTE,2,13.99,27.98
7,3,FERNANDA,TORRES,FERNANDA TORRES,PASTA DE DENTE,7,6.99,48.93
8,2,FRANCIELE,OLIVEIRA,FRANCIELE OLIVEIRA,HIDRATANTE,4,22.39,89.56